name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: endobit/ci/.github/workflows/go-lint.yaml@v1.3.2
  test:
    uses: endobit/ci/.github/workflows/go-test.yaml@v1.3.2
    secrets: inherit
